defaults:
  - env/realworld_cap_tightening@env.train
  - env/realworld_cap_tightening@env.eval
  - model/cnn_policy@actor.model
  - hybrid_engines/fsdp@actor.fsdp_config
  - weight_syncer/patch_syncer@weight_syncer
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 2
  component_placement:
    actor: 
      node_group: "4090"
      placement: 0 # Local GPU rank in the 4090 node group (n for the n+1 th GPU)
    env:
      node_group: franka
      placement: 0 # Local robot rank in the franka node group (n for the n+1 th robot)
    rollout:
      node_group: "4090"
      placement: 0 # Local GPU rank in the 4090 node group (n for the n+1 th GPU)
  node_groups:
    - label: "4090" # GPU node group
      node_ranks: 0 # The ranks of the nodes to be included in this group， change this if your training node is not rank 0
    - label: franka
      node_ranks: 1 # Change this if your robot node is not rank 1
      hardware:
        type: Franka
        configs:
          - robot_ip: ROBOT_IP # Replace with your robot's IP address
            node_rank: 1

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "sac_mlp"
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 8000
  max_steps: -1

  only_eval: False
  val_check_interval: -1
  save_interval: -1

  resume_dir: null # Optional: path to a saved checkpoint directory, such as 'checkpoints/global_step_10'. If not None, it will be used to resume training.
  ckpt_path: null  # Optional: path to a .pt checkpoint. If not None, it will be loaded after the model is instantiated (for evaluation).

algorithm:
  update_epoch: 32
  group_size: 1
  agg_q: min # or mean
  actor_agg_q: mean
  enable_drq: False

  backup_entropy: False
  critic_subsample_size: 2

  adv_type: embodied_sac
  loss_type: embodied_sac
  loss_agg_func: "token-mean"
  
  bootstrap_type: standard
  gamma: 0.96
  tau: 0.005  # Soft update coefficient for target networks

  entropy_tuning:
    alpha_type: softplus # choose from ["softplus", "exp", "fixed_alpha"], set to "softplus" or "exp" to enable automatic entropy tuning
    initial_alpha: 0.01  # Initial temperature value
    target_entropy: -3  # Target entropy (-action_dim)
    optim:
      lr: 3.0e-4  # Learning rate for temperature parameter
      lr_scheduler: torch_constant
      clip_grad: 10.0
  
  critic_actor_ratio: 4
  # Replay buffer settings
  replay_buffer:
    enable_cache: True
    cache_size: 200 # number of trajectories cached in memory
    min_buffer_size: 1  # Minimum buffer size before training starts (in number of trajectories). If set too large, it will take a long time to start real-world training 
    sample_window_size: 200 # number of latest trajectories to sample from for replay buffer
    auto_save: False

  demo_buffer:
    enable_cache: True
    cache_size: 200 # number of trajectories cached in memory
    min_buffer_size: 1
    sample_window_size: 200 # number of latest trajectories to sample from for demo buffer
    load_path: "/path/to/demo_data"
    auto_save: False

  target_update_freq: 1  # Frequency of target network updates

env:
  group_name: "EnvGroup"
  enable_offload: False

  train:
    ignore_terminations: False
    total_num_envs: 1
    teleop: spacemouse
    keyboard_reward_wrapper: single_stage # options: "single_stage", "multi_stage"
    no_gripper: False
    max_steps_per_rollout_epoch: 200
    max_episode_steps: 400
    override_cfg:
      use_dense_reward: False
      target_ee_pose: TARGET_EE_POSE
      enable_gripper_penalty: False
      max_num_steps: 400
    
  eval:
    rollout_epoch: 1
    total_num_envs: 1

rollout:
  group_name: "RolloutGroup"
  backend: "huggingface"
  enable_offload: False
  pipeline_stage_num: 1

  collect_transitions: True
  collect_prev_infos: False

  model:
    action_dim: 7
    model_path: "/path/to/RLinf-ResNet10-pretrained" # https://huggingface.co/RLinf/RLinf-ResNet10-pretrained
    precision: ${actor.model.precision}
    num_q_heads: 10

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"

  micro_batch_size: 256
  global_batch_size: 256
  seed: 1234
  enable_offload: False

  model:
    model_path: "/path/to/RLinf-ResNet10-pretrained" # https://huggingface.co/RLinf/RLinf-ResNet10-pretrained
    num_q_heads: 10
    state_dim: 19
    action_dim: 7

  optim:
    lr: 1.0e-4  # Lower learning rate for SAC
    clip_grad: 10.0
    lr_scheduler: torch_constant

  critic_optim:
    clip_grad: 10.0
    lr: 3e-4
    lr_scheduler: torch_constant

  # Override the default values in hybrid_engines/fsdp
  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False

weight_syncer:
  nccl_max_ctas: 32 # Max CTAs (Compute Thread Array, the compute resource of GPUs) for sync weight communication. Higher values consume more GPU resources, and thus sync weight is faster but could affect rollout speed in async mode. Positive integer 1 to 32. Default 32.
