defaults:
  - env/realworld_peg_insertion@env.eval
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 2
  component_placement:
    env:
      node_group: franka
      placement: 0
  node_groups:
    - label: franka
      node_ranks: 0-1
      hardware:
        type: Franka
        configs:
          - robot_ip: ROBOT_IP # Replace with your robot's IP address
            node_rank: 0
            camera_serials:
              - "ZED_SERIAL_1" # Replace with your ZED camera serial numbers
            camera_type: zed
            gripper_type: robotiq
            gripper_connection: "/dev/ttyUSB0"
            controller_node_rank: 1

runner:
  task_type: embodied
  logger:
    log_path: null
    project_name: rlinf
    experiment_name: "collect-data-zed-robotiq"
    logger_backends: ["tensorboard"]
  num_data_episodes: 20
  record_task_description: False

env:
  group_name: "EnvGroup"
  eval:
    ignore_terminations: False
    auto_reset: False
    teleop: spacemouse
    override_cfg:
      target_ee_pose: TARGET_EE_POSE # Replace with your target end-effector pose
      success_hold_steps: 1

    data_collection:
      enabled: True
      save_dir: ${runner.logger.log_path}/collected_data
      export_format: "lerobot"
      only_success: True
      robot_type: "panda"
      fps: 10
