defaults:
  - env/realworld_peg_insertion@env.eval
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:REWARD_PATH}/config/

cluster:
  num_nodes: 2
  component_placement:
    env:
      node_group: franka
      placement: 0
    reward:
      node_group: "4090"
      placement: 0
  node_groups:
    - label: "4090"
      node_ranks: 0
    - label: franka
      node_ranks: 1
      hardware:
        type: Franka
        configs:
          - robot_ip: ROBOT_IP
            node_rank: 1

runner:
  task_type: embodied
  logger:
    log_path: null
    project_name: rlinf
    experiment_name: "realworld-teleop"
    logger_backends: ["tensorboard"]

env:
  group_name: "EnvGroup"
  eval:
    no_gripper: True
    ignore_terminations: False
    auto_reset: True
    teleop: spacemouse
    max_episode_steps: 10000
    override_cfg:
      target_ee_pose: TARGET_EE_POSE

reward:
  use_reward_model: True
  use_reward_prob: True  # log raw sigmoid probs to terminal when True
  group_name: "RewardGroup"
  standalone_realworld: True
  reward_mode: "per_step"
  reward_threshold: 0.2
  reward_weight: 1.0
  env_reward_weight: 0.0
  model:
    model_path: path/to/model
    model_type: "resnet"
    pretrained: False
    arch: "resnet18"
    hidden_dim: 256
    dropout: 0
    image_size: [3, 128, 128]
    normalize: true
    precision: "fp32"
