model_type: "openpi_rlinf"
precision: null
pi05: False
is_lora: False
lora_rank: 32
use_proprio: True
num_action_chunks: 5
action_dim: 7
num_steps: 4
add_value_head: True
openpi:
  task: rl
  config_name: "pi0_libero"
  num_images_in_input: 2
  action_chunk: ${..num_action_chunks}
  num_steps: ${..num_steps}
  action_env_dim: ${..action_dim}
  model_action_dim: 32
  paligemma_variant: "gemma_2b"
  action_expert_variant: "gemma_300m"
  max_token_len: 48
  discrete_state_input: False
  value_after_vlm: True
  value_vlm_mode: "mean_token"
  detach_critic_input: True
  joint_logprob: False
  ignore_last: False
  noise_level: 0.5
  noise_method: "flow_sde"
  train_expert_only: True

